#!/usr/bin/env python3
"""Download only explicitly reusable Wikimedia Commons images listed in data/media.json.

Uses Python standard library only. It resolves the original file URL through
the MediaWiki API, saves the binary under each asset's local_target, and writes
media/ATTRIBUTION.md.

It deliberately skips:
- OOPT images pending permission;
- entries whose reuse field does not start with "allowed";
- entries without a Wikimedia Commons source page;
- entries whose exact license still needs verification.
"""
from __future__ import annotations

import json
import sys
import urllib.parse
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MEDIA_JSON = ROOT / "data" / "media.json"
ATTRIBUTION = ROOT / "media" / "ATTRIBUTION.md"
API = "https://commons.wikimedia.org/w/api.php"
USER_AGENT = "PeresheekGO-media-downloader/0.1 (licensed media import)"

ALLOWED_LICENSES = (
    "Public domain",
    "CC0",
    "CC BY ",
    "CC BY-SA ",
)


def commons_title(source_page: str) -> str:
    parsed = urllib.parse.urlparse(source_page)
    slug = urllib.parse.unquote(parsed.path.rsplit("/", 1)[-1])
    if not slug.startswith("File:"):
        raise ValueError("Not a Commons File page")
    return slug.replace("_", " ")


def resolve_original(title: str) -> dict:
    query = urllib.parse.urlencode({
        "action": "query",
        "format": "json",
        "prop": "imageinfo",
        "iiprop": "url|extmetadata",
        "titles": title,
    })
    req = urllib.request.Request(
        f"{API}?{query}",
        headers={"User-Agent": USER_AGENT},
    )
    with urllib.request.urlopen(req, timeout=30) as response:
        payload = json.load(response)
    page = next(iter(payload["query"]["pages"].values()))
    info = page.get("imageinfo", [None])[0]
    if not info or not info.get("url"):
        raise RuntimeError(f"Commons did not return an original URL for {title}")
    return info


def download(url: str, target: Path) -> None:
    target.parent.mkdir(parents=True, exist_ok=True)
    req = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    with urllib.request.urlopen(req, timeout=60) as response:
        data = response.read()
    if len(data) < 1024:
        raise RuntimeError(f"Downloaded file is unexpectedly small: {len(data)} bytes")
    target.write_bytes(data)


def main() -> int:
    data = json.loads(MEDIA_JSON.read_text(encoding="utf-8"))
    assets = data.get("reusable_assets", [])
    imported = []
    skipped = []
    failed = []

    for asset in assets:
        aid = asset.get("asset_id", "<unknown>")
        source = asset.get("source_page", "")
        license_name = asset.get("license", "")
        reuse = asset.get("reuse", "")
        local_target = asset.get("local_target")

        if not (
            source.startswith("https://commons.wikimedia.org/wiki/File:")
            and reuse.startswith("allowed")
            and local_target
            and any(license_name.startswith(x) for x in ALLOWED_LICENSES)
        ):
            skipped.append((aid, "license/source not eligible for automatic import"))
            continue

        try:
            title = commons_title(source)
            info = resolve_original(title)
            target = ROOT / local_target
            download(info["url"], target)
            imported.append((asset, target.relative_to(ROOT).as_posix()))
            print(f"OK   {aid} -> {target.relative_to(ROOT)}")
        except Exception as exc:
            failed.append((aid, str(exc)))
            print(f"FAIL {aid}: {exc}", file=sys.stderr)

    ATTRIBUTION.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Photo attribution",
        "",
        "This file is generated by `scripts/download_media.py`.",
        "Always keep this attribution information with redistributed images.",
        "",
    ]
    for asset, path in imported:
        place_ids = asset.get("place_ids") or [asset.get("place_id")]
        lines += [
            f"## {asset.get('asset_id')}",
            f"- Local file: `{path}`",
            f"- Place IDs: {', '.join(x for x in place_ids if x)}",
            f"- Author: {asset.get('author', 'See source page')}",
            f"- License: {asset.get('license')}",
            f"- License URL: {asset.get('license_url') or 'See source page'}",
            f"- Source: {asset.get('source_page')}",
            "",
        ]
    ATTRIBUTION.write_text("\n".join(lines), encoding="utf-8")

    print(f"\nImported: {len(imported)}; skipped: {len(skipped)}; failed: {len(failed)}")
    print(f"Attribution: {ATTRIBUTION.relative_to(ROOT)}")
    if skipped:
        print("\nSkipped:")
        for aid, why in skipped:
            print(f"  - {aid}: {why}")
    return 1 if failed else 0


if __name__ == "__main__":
    raise SystemExit(main())
